### ISSUE TITLE
Create/Push app feature support

### ISSUE THREAD

**Issue by vshelvankar** [cloudfoundry-community/go-cfclient#160]
Hi Team,

We are looking for Create/Push app feature support in the cfclient. Any plans of supporting it with an ETA. Does anyone has picked this up to proceed with. If not we are interested to contribute on this and use for our project.

**Comment by lnguyen** [comment]
I don't think that might be a good idea. There's alot of calls it takes to
do this I would just recommend scripting around cli

On Dec 13, 2017 10:31 AM, "vshelvankar" <notifications@github.com> wrote:

Hi Team,

We are looking for Create/Push app feature support in the cfclient. Any
plans of supporting it with an ETA. Does anyone has picked this up to
proceed with. If not we are interested to contribute on this and use for
our project.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry-community/go-cfclient/issues/160>, or mute
the thread

**Comment by vshelvankar** [comment]
Thanks lnguyen  for the comment,

We have a use case where we want to run an app in a binary_buildpack where i do not have an option of cf cli installed. I wanted to push few apps dynamically and using a client. JAVA's CF Client has these feature and looks a valid case to have it here for those who wants to do these operations without cli installed.

**Comment by vshelvankar** [comment]
Also i believe the purpose of SDKs or language specific Clients are to provide the interfaces to perform all operations incase the user do not want to use the REST/CLI directly

**Comment by cappyzawa** [comment]
@vshelvankar 
> Also i believe the purpose of SDKs or language specific Clients are to provide the interfaces to perform all operations incase the user do not want to use the REST/CLI directly
I totally agree.

**Comment by sneal** [comment]
I've implemented `cf push` like functionality using the primitives in this library. I'm sure others have as well. Unfortunately we'd likely never match exactly what the CF CLI does under the covers. The CLI does a surprising amount of work "just to push" an app. Having said that, I think it's a good idea and avoids other from having to reinvent the wheel or install the CLI.

**Comment by sneal** [comment]
A new [PushAppOperation](https://github.com/cloudfoundry-community/go-cfclient/blob/8c19d8533d9bc4e431169489e213b9a6984e5fad/operation/push.go#L28) was added in the v3 client.
