### ISSUE TITLE
go-cfcliient is not updated according to code.cloudfoundry.org/cli@v8.4.0

### ISSUE THREAD

**Issue by olyakrasnozhon** [cloudfoundry-community/go-cfclient#310]
Hi,
I need to start using v3 client instead of v2 in my terraform-provider-cf. After some investigation I see that the new resources I need and their CRUD APIs are added in code.cloudfoundry.org/cli v8.4.0 (https://github.com/cloudfoundry/cli/tree/v8.4.0). 
But I can't import this library directly, the error is - 
"go get: code.cloudfoundry.org/cli@v8.4.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v8".

I went over another libraries that I probably could use instead:
- https://github.com/cloudfoundry-community/go-cfclient (latest)
- https://github.com/cloudfoundry-community/cloudfoundry-cli (latest and v0.0.11-complete-api) 
 
But they don't contains the newest APIs: for instance, go-cfclient contains the resource we need v3ServiceCredentialsBinding, but doesn't contain Create/Delete APIs for it. 

Are you planning to update the go-cfclient according to v8.4.0 of code.cloudfoundry.org/cli soon?

Thanks
Best regards,
Olga

**Comment by sneal** [comment]
Hi Olga, we don't have any plans to add specific functionality to go-cfclient. Functionality gets added as users of this library need it. If you'd like to add the resources you need we'd certainly accept a PR complete with tests.

FWIW - I wouldn't recommend using https://github.com/cloudfoundry-community/cloudfoundry-cli as it's a fork of https://github.com/cloudfoundry/cli. I believe the CF CLI team recommends consuming their code via shell execution instead of importing it as a library.
