### ISSUE TITLE
How to get token refreshed

### ISSUE THREAD

**Issue by lizzha** [cloudfoundry-community/go-cfclient#34]
By default the token is valid for 10 minutes. How to get the token refreshed after it expires?

**Comment by srbry** [comment]
Hi @lizzha by default this client will use the oauth refresh tokens to get a new token automatically whenever a token has expired. This has the caveat of refresh tokens themselves actually having an expiry (something like a few days). In order to get a new token after that you would basically want to recreate the client to kick off the oauth process from the very start.

**Comment by altenhof** [comment]
Hi,

we recently faced the same issue where the library failed to renew the refresh token.
It turned out that using a CF user/password for login will not work when it comes to renewing the refresh token. If that has to be refreshed the underlying oauth client will use the token_url which then requires a UAA client/secret, not a CF user/password.

Best

Michael

**Comment by drnic** [comment]
Is this an improvement that can be brought into this lib?
